pipeline:
   agent: any
   environment:
    CURRENTENV: QA
    ADMINUSERNAME: "Admin"
    ADMINPASSWORD: "admin123"
   stages:
    - stage: Install Dependecies
      steps:
      script:
        - echo "Installing Dependencies......"
        - npm install
        - npx playwright install
    - stage: Run Playwright Tests
      - echo "Running playwright test"
      - npx playwright test

    - stage:
      steps:
      script:
        - cleanWs();
      